# encoding: utf-8
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Team.destroy_all
t1 = Team.create!(name: 'Brasil', logotipo: 'brasil.png', abbrev: 'BRA')
t2 = Team.create!(name: 'Croácia', logotipo: 'croacia.png', abbrev: 'CRO')
t3 = Team.create!(name: 'México', logotipo: 'mexico.png', abbrev: 'MEX')
t4 = Team.create!(name: 'Camarões', logotipo: 'camaroes.png', abbrev: 'CMR')
t5 = Team.create!(name: 'Espanha', logotipo: 'espanha.png', abbrev: 'ESP')
t6 = Team.create!(name: 'Holanda', logotipo: 'holanda.png', abbrev: 'HOL')
t7 = Team.create!(name: 'Chile', logotipo: 'chile.png', abbrev: 'CHI')
t8 = Team.create!(name: 'Austrália', logotipo: 'australia.png', abbrev: 'AUS')
t9 = Team.create!(name: 'Colômbia', logotipo: 'colombia.png', abbrev: 'COL')
t10 = Team.create!(name: 'Grécia', logotipo: 'grecia.png', abbrev: 'GRE')
t11 = Team.create!(name: 'Costa do Marfim', logotipo: 'costa-do-marfim.png', abbrev: 'CMF')
t12 = Team.create!(name: 'Japão', logotipo: 'japao.png', abbrev: 'JAP') 
t13 = Team.create!(name: 'Uruguai', logotipo: 'uruguai.png', abbrev: 'URU')
t14 = Team.create!(name: 'Costa Rica', logotipo: 'costa-rica.png', abbrev: 'CRC')
t15 = Team.create!(name: 'Inglaterra', logotipo: 'inglaterra.png', abbrev: 'ING')
t16 = Team.create!(name: 'Itália', logotipo: 'italia.png', abbrev: 'ITA')
t17 = Team.create!(name: 'Suíça', logotipo: 'suica.png', abbrev: 'SUI')
t18 = Team.create!(name: 'Equador', logotipo: 'equador.png', abbrev: 'EQU')
t19 = Team.create!(name: 'França', logotipo: 'franca.png', abbrev: 'FRA')
t20 = Team.create!(name: 'Honduras', logotipo: 'honduras.png', abbrev: 'HON')
t21 = Team.create!(name: 'Argentina', logotipo: 'argentina.png', abbrev: 'ARG')
t22 = Team.create!(name: 'Bósnia', logotipo: 'bosnia.png', abbrev: 'BOS')
t23 = Team.create!(name: 'Irã', logotipo: 'ira.png', abbrev: 'IRA')
t24 = Team.create!(name: 'Nigéria', logotipo: 'nigeria.png', abbrev: 'NIG')
t25 = Team.create!(name: 'Alemanha', logotipo: 'alemanha.png', abbrev: 'ALE')
t26 = Team.create!(name: 'Portugal', logotipo: 'portugal.png', abbrev: 'POR')
t27 = Team.create!(name: 'Gana', logotipo: 'gana.png', abbrev: 'GAN')
t28 = Team.create!(name: 'Estados Unidos', logotipo: 'eua.png', abbrev: 'EUA')
t29 = Team.create!(name: 'Bélgica', logotipo: 'belgica.png', abbrev: 'BEL')
t30 = Team.create!(name: 'Argélia', logotipo: 'argelia.png', abbrev: 'ALG')
t31 = Team.create!(name: 'Rússia', logotipo: 'russia.png', abbrev: 'RUS')
t32 = Team.create!(name: 'Coréia do Sul', logotipo: 'coreia-do-sul.png', abbrev: 'COR')

#Jogos da primeira fase
Game.destroy_all
g1 = Game.create!(local: 'Arena Corinthians', gamedate: '2014-06-12', gametime: '17:00:00', computed: false, finished: false, closed: false)
g2 = Game.create!(local: 'Arena das Dunas', gamedate: '2014-06-13', gametime: '13:00:00', computed: false, finished: false, closed: false)
g3 = Game.create!(local: 'Fonte Nova', gamedate: '2014-06-13', gametime: '16:00:00', computed: false, finished: false, closed: false)
g4 = Game.create!(local: 'Arena Pantanal', gamedate: '2014-06-13', gametime: '19:00:00', computed: false, finished: false, closed: false)
g5 = Game.create!(local: 'Mineirão', gamedate: '2014-06-14', gametime: '13:00:00', computed: false, finished: false, closed: false)
g6 = Game.create!(local: 'Castelão', gamedate: '2014-06-14', gametime: '16:00:00', computed: false, finished: false, closed: false)
g7 = Game.create!(local: 'Arena da Amazônia', gamedate: '2014-06-14', gametime: '18:00:00', computed: false, finished: false, closed: false)
g8 = Game.create!(local: 'Arena Pernambuco', gamedate: '2014-06-14', gametime: '22:00:00', computed: false, finished: false, closed: false)
g9 = Game.create!(local: 'Mané Garrincha', gamedate: '2014-06-15', gametime: '13:00:00', computed: false, finished: false, closed: false)
g10 = Game.create!(local: 'Beira Rio', gamedate: '2014-06-15', gametime: '16:00:00', computed: false, finished: false, closed: false)
g11 = Game.create!(local: 'Maracanã', gamedate: '2014-06-15', gametime: '19:00:00', computed: false, finished: false, closed: false)
g12 = Game.create!(local: 'Fonte Nova', gamedate: '2014-06-16', gametime: '13:00:00', computed: false, finished: false, closed: false)
g13 = Game.create!(local: 'Arena da Baixada', gamedate: '2014-06-16', gametime: '16:00:00', computed: false, finished: false, closed: false)
g14 = Game.create!(local: 'Arena das Dunas', gamedate: '2014-06-16', gametime: '19:00:00', computed: false, finished: false, closed: false)
g15 = Game.create!(local: 'Mineirão', gamedate: '2014-06-17', gametime: '13:00:00', computed: false, finished: false, closed: false)
g16 = Game.create!(local: 'Fonte Nova', gamedate: '2014-06-17', gametime: '16:00:00', computed: false, finished: false, closed: false)
g17 = Game.create!(local: 'Arena Pantanal', gamedate: '2014-06-17', gametime: '19:00:00', computed: false, finished: false, closed: false)
g18 = Game.create!(local: 'Beira Rio', gamedate: '2014-06-18', gametime: '13:00:00', computed: false, finished: false, closed: false)
g19 = Game.create!(local: 'Maracanã', gamedate: '2014-06-18', gametime: '16:00:00', computed: false, finished: false, closed: false)
g20 = Game.create!(local: 'Arena da Amazônia', gamedate: '2014-06-18', gametime: '18:00:00', computed: false, finished: false, closed: false)
g21 = Game.create!(local: 'Mané Garrincha', gamedate: '2014-06-19', gametime: '13:00:00', computed: false, finished: false, closed: false)
g22 = Game.create!(local: 'Arena Corinthians', gamedate: '2014-06-19', gametime: '16:00:00', computed: false, finished: false, closed: false)
g23 = Game.create!(local: 'Arena das Dunas', gamedate: '2014-06-19', gametime: '19:00:00', computed: false, finished: false, closed: false)
g24 = Game.create!(local: 'Arena Pernambuco', gamedate: '2014-06-20', gametime: '13:00:00', computed: false, finished: false, closed: false)
g25 = Game.create!(local: 'Fonte Nova', gamedate: '2014-06-20', gametime: '16:00:00', computed: false, finished: false, closed: false)
g26 = Game.create!(local: 'Arena da Baixada', gamedate: '2014-06-20', gametime: '19:00:00', computed: false, finished: false, closed: false)
g27 = Game.create!(local: 'Mineirão', gamedate: '2014-06-21', gametime: '13:00:00', computed: false, finished: false, closed: false)
g28 = Game.create!(local: 'Castelão', gamedate: '2014-06-21', gametime: '16:00:00', computed: false, finished: false, closed: false)
g29 = Game.create!(local: 'Arena Pantanal', gamedate: '2014-06-21', gametime: '19:00:00', computed: false, finished: false, closed: false)
g30 = Game.create!(local: 'Maracanã', gamedate: '2014-06-22', gametime: '13:00:00', computed: false, finished: false, closed: false)
g31 = Game.create!(local: 'Beira Rio', gamedate: '2014-06-22', gametime: '16:00:00', computed: false, finished: false, closed: false)
g32 = Game.create!(local: 'Arena da Amazônia', gamedate: '2014-06-22', gametime: '18:00:00', computed: false, finished: false, closed: false)
g33 = Game.create!(local: 'Arena da Baixada', gamedate: '2014-06-23', gametime: '13:00:00', computed: false, finished: false, closed: false)
g34 = Game.create!(local: 'Arena Corinthians', gamedate: '2014-06-23', gametime: '13:00:00', computed: false, finished: false, closed: false)
g35 = Game.create!(local: 'Mané Garrincha', gamedate: '2014-06-23', gametime: '17:00:00', computed: false, finished: false, closed: false)
g36 = Game.create!(local: 'Arena Pernambuco', gamedate: '2014-06-23', gametime: '17:00:00', computed: false, finished: false, closed: false)
g37 = Game.create!(local: 'Arena das Dunas', gamedate: '2014-06-24', gametime: '13:00:00', computed: false, finished: false, closed: false)
g38 = Game.create!(local: 'Mineirão', gamedate: '2014-06-24', gametime: '13:00:00', computed: false, finished: false, closed: false)
g39 = Game.create!(local: 'Arena Pantanal', gamedate: '2014-06-24', gametime: '17:00:00', computed: false, finished: false, closed: false)
g40 = Game.create!(local: 'Castelão', gamedate: '2014-06-24', gametime: '17:00:00', computed: false, finished: false, closed: false)
g41 = Game.create!(local: 'Beira Rio', gamedate: '2014-06-25', gametime: '13:00:00', computed: false, finished: false, closed: false)
g42 = Game.create!(local: 'Fonte Nova', gamedate: '2014-06-25', gametime: '13:00:00', computed: false, finished: false, closed: false)
g43 = Game.create!(local: 'Arena da Amazônia', gamedate: '2014-06-25', gametime: '17:00:00', computed: false, finished: false, closed: false)
g44 = Game.create!(local: 'Maracanã', gamedate: '2014-06-25', gametime: '17:00:00', computed: false, finished: false, closed: false)
g45 = Game.create!(local: 'Arena Pernambuco', gamedate: '2014-06-26', gametime: '13:00:00', computed: false, finished: false, closed: false)
g46 = Game.create!(local: 'Mané Garrincha', gamedate: '2014-06-26', gametime: '13:00:00', computed: false, finished: false, closed: false)
g47 = Game.create!(local: 'Arena Corinthians', gamedate: '2014-06-26', gametime: '17:00:00', computed: false, finished: false, closed: false)
g48 = Game.create!(local: 'Arena da Baixada', gamedate: '2014-06-26', gametime: '17:00:00', computed: false, finished: false, closed: false)

#Jogos das oitavas

#Jogos das quartas

#Jogos das semis

#Jogos do 3o colocado

#Final

MatchResult.destroy_all
MatchResult.create!(team_id: t1.id, game_id: g1.id, goals: 0)
MatchResult.create!(team_id: t2.id, game_id: g1.id, goals: 0)
MatchResult.create!(team_id: t3.id, game_id: g2.id, goals: 0)
MatchResult.create!(team_id: t4.id, game_id: g2.id, goals: 0)
MatchResult.create!(team_id: t5.id, game_id: g3.id, goals: 0)
MatchResult.create!(team_id: t6.id, game_id: g3.id, goals: 0)
MatchResult.create!(team_id: t7.id, game_id: g4.id, goals: 0)
MatchResult.create!(team_id: t8.id, game_id: g4.id, goals: 0)
MatchResult.create!(team_id: t9.id, game_id: g5.id, goals: 0)
MatchResult.create!(team_id: t10.id, game_id: g5.id, goals: 0)
MatchResult.create!(team_id: t13.id, game_id: g6.id, goals: 0)
MatchResult.create!(team_id: t14.id, game_id: g6.id, goals: 0)
MatchResult.create!(team_id: t15.id, game_id: g7.id, goals: 0)
MatchResult.create!(team_id: t16.id, game_id: g7.id, goals: 0)
MatchResult.create!(team_id: t11.id, game_id: g8.id, goals: 0)
MatchResult.create!(team_id: t12.id, game_id: g8.id, goals: 0)
MatchResult.create!(team_id: t17.id, game_id: g9.id, goals: 0)
MatchResult.create!(team_id: t18.id, game_id: g9.id, goals: 0)
MatchResult.create!(team_id: t19.id, game_id: g10.id, goals: 0)
MatchResult.create!(team_id: t20.id, game_id: g10.id, goals: 0)
MatchResult.create!(team_id: t21.id, game_id: g11.id, goals: 0)
MatchResult.create!(team_id: t22.id, game_id: g11.id, goals: 0)
MatchResult.create!(team_id: t25.id, game_id: g12.id, goals: 0)
MatchResult.create!(team_id: t26.id, game_id: g12.id, goals: 0)
MatchResult.create!(team_id: t23.id, game_id: g13.id, goals: 0)
MatchResult.create!(team_id: t24.id, game_id: g13.id, goals: 0)
MatchResult.create!(team_id: t27.id, game_id: g14.id, goals: 0)
MatchResult.create!(team_id: t28.id, game_id: g14.id, goals: 0)
MatchResult.create!(team_id: t29.id, game_id: g15.id, goals: 0)
MatchResult.create!(team_id: t30.id, game_id: g15.id, goals: 0)
MatchResult.create!(team_id: t1.id, game_id: g16.id, goals: 0)
MatchResult.create!(team_id: t3.id, game_id: g16.id, goals: 0)
MatchResult.create!(team_id: t31.id, game_id: g17.id, goals: 0)
MatchResult.create!(team_id: t32.id, game_id: g17.id, goals: 0)
MatchResult.create!(team_id: t6.id, game_id: g18.id, goals: 0)
MatchResult.create!(team_id: t8.id, game_id: g18.id, goals: 0)
MatchResult.create!(team_id: t5.id, game_id: g19.id, goals: 0)
MatchResult.create!(team_id: t7.id, game_id: g19.id, goals: 0)
MatchResult.create!(team_id: t2.id, game_id: g20.id, goals: 0)
MatchResult.create!(team_id: t4.id, game_id: g20.id, goals: 0)
MatchResult.create!(team_id: t9.id, game_id: g21.id, goals: 0)
MatchResult.create!(team_id: t11.id, game_id: g21.id, goals: 0)
MatchResult.create!(team_id: t13.id, game_id: g22.id, goals: 0)
MatchResult.create!(team_id: t15.id, game_id: g22.id, goals: 0)
MatchResult.create!(team_id: t10.id, game_id: g23.id, goals: 0)
MatchResult.create!(team_id: t12.id, game_id: g23.id, goals: 0)
MatchResult.create!(team_id: t14.id, game_id: g24.id, goals: 0)
MatchResult.create!(team_id: t16.id, game_id: g24.id, goals: 0)
MatchResult.create!(team_id: t17.id, game_id: g25.id, goals: 0)
MatchResult.create!(team_id: t19.id, game_id: g25.id, goals: 0)
MatchResult.create!(team_id: t18.id, game_id: g26.id, goals: 0)
MatchResult.create!(team_id: t20.id, game_id: g26.id, goals: 0)
MatchResult.create!(team_id: t21.id, game_id: g27.id, goals: 0)
MatchResult.create!(team_id: t23.id, game_id: g27.id, goals: 0)
MatchResult.create!(team_id: t25.id, game_id: g28.id, goals: 0)
MatchResult.create!(team_id: t27.id, game_id: g28.id, goals: 0)
MatchResult.create!(team_id: t22.id, game_id: g29.id, goals: 0)
MatchResult.create!(team_id: t24.id, game_id: g29.id, goals: 0)
MatchResult.create!(team_id: t29.id, game_id: g30.id, goals: 0)
MatchResult.create!(team_id: t31.id, game_id: g30.id, goals: 0)
MatchResult.create!(team_id: t30.id, game_id: g31.id, goals: 0)
MatchResult.create!(team_id: t32.id, game_id: g31.id, goals: 0)
MatchResult.create!(team_id: t26.id, game_id: g32.id, goals: 0)
MatchResult.create!(team_id: t28.id, game_id: g32.id, goals: 0)
MatchResult.create!(team_id: t5.id, game_id: g33.id, goals: 0)
MatchResult.create!(team_id: t8.id, game_id: g33.id, goals: 0)
MatchResult.create!(team_id: t6.id, game_id: g34.id, goals: 0)
MatchResult.create!(team_id: t7.id, game_id: g34.id, goals: 0)
MatchResult.create!(team_id: t1.id, game_id: g35.id, goals: 0)
MatchResult.create!(team_id: t4.id, game_id: g35.id, goals: 0)
MatchResult.create!(team_id: t2.id, game_id: g36.id, goals: 0)
MatchResult.create!(team_id: t3.id, game_id: g36.id, goals: 0)
MatchResult.create!(team_id: t13.id, game_id: g37.id, goals: 0)
MatchResult.create!(team_id: t16.id, game_id: g37.id, goals: 0)
MatchResult.create!(team_id: t14.id, game_id: g38.id, goals: 0)
MatchResult.create!(team_id: t15.id, game_id: g38.id, goals: 0)
MatchResult.create!(team_id: t9.id, game_id: g39.id, goals: 0)
MatchResult.create!(team_id: t12.id, game_id: g39.id, goals: 0)
MatchResult.create!(team_id: t10.id, game_id: g40.id, goals: 0)
MatchResult.create!(team_id: t11.id, game_id: g40.id, goals: 0)
MatchResult.create!(team_id: t21.id, game_id: g41.id, goals: 0)
MatchResult.create!(team_id: t24.id, game_id: g41.id, goals: 0)
MatchResult.create!(team_id: t22.id, game_id: g42.id, goals: 0)
MatchResult.create!(team_id: t23.id, game_id: g42.id, goals: 0)
MatchResult.create!(team_id: t17.id, game_id: g43.id, goals: 0)
MatchResult.create!(team_id: t20.id, game_id: g43.id, goals: 0)
MatchResult.create!(team_id: t18.id, game_id: g44.id, goals: 0)
MatchResult.create!(team_id: t19.id, game_id: g44.id, goals: 0)
MatchResult.create!(team_id: t25.id, game_id: g45.id, goals: 0)
MatchResult.create!(team_id: t28.id, game_id: g45.id, goals: 0)
MatchResult.create!(team_id: t26.id, game_id: g46.id, goals: 0)
MatchResult.create!(team_id: t27.id, game_id: g46.id, goals: 0)
MatchResult.create!(team_id: t29.id, game_id: g47.id, goals: 0)
MatchResult.create!(team_id: t32.id, game_id: g47.id, goals: 0)
MatchResult.create!(team_id: t30.id, game_id: g48.id, goals: 0)
MatchResult.create!(team_id: t31.id, game_id: g48.id, goals: 0)

User.destroy_all
user = User.create!(name: 'Admin', lastname: 'Bolão', password: 'admin12345', password_confirmation: 'admin12345', email: 'gilliard@quadrit.com.br', email_confirmation: 'gilliard@quadrit.com.br', typeof: User::USER_TYPE[:ADMIN][:id], score: 0)